name: example
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.19.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  kbspinningwheel:
    path: ../

flutter:
  uses-material-design: true

  assets:
    - assets/images/wheel-6-300.png
    - assets/images/roulette-8-300.png
    - assets/images/roulette-center-300.png
